apiVersion: v1
kind: Secret
metadata:
  name: {{ template "AppCtx.squashautoName" . }}-secret
  labels: {{ include "AppCtx.squashLabels" . | nindent 4 }} 
data:
  squashtf.pub: {{ .Values.squashauto.trustedKey.pub_key }}