{{- if .Values.squashauto.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "AppCtx.squashautoName" . }}-cm
  labels: {{ include "AppCtx.squashLabels" . | nindent 4 }}
data:
{{- end }}
