{{- if .Values.squash.enabled }}
{{- if not .Values.squash.pgCredentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "AppCtx.squashName" . }}-credentials
  labels: {{ include "AppCtx.labels" . | nindent 4 }}
type: Opaque
data:
  SQTM_DB_USERNAME: {{ .Values.squash.pgCredentials.user | b64enc }}
  SQTM_DB_PASSWORD: {{ .Values.squash.pgCredentials.pwd | b64enc }}
{{- end }}
{{- end }}
